/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;

/**
 *
 * @author User
 */
public class CADASTRAR extends javax.swing.JFrame {
   LinkedList<Filmes> listaFilmes;
    
     
    /**
     * Creates new form CADASTRAR
     */
    public CADASTRAR(LinkedList<Filmes> listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
    }

      

   
   
     /* 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBFilmesNormais = new javax.swing.JButton();
        jBFilmes3d = new javax.swing.JButton();
        jBRealidadeVirtual = new javax.swing.JButton();
        jBEspecial = new javax.swing.JButton();
        jLCadastrarFilmes = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jBFilmesNormais.setBackground(new java.awt.Color(255, 102, 102));
        jBFilmesNormais.setForeground(new java.awt.Color(255, 255, 255));
        jBFilmesNormais.setText("Filmes Normais");
        jBFilmesNormais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFilmesNormaisActionPerformed(evt);
            }
        });

        jBFilmes3d.setBackground(new java.awt.Color(255, 255, 255));
        jBFilmes3d.setForeground(new java.awt.Color(255, 102, 102));
        jBFilmes3d.setText("Filmes 3d");
        jBFilmes3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFilmes3dActionPerformed(evt);
            }
        });

        jBRealidadeVirtual.setBackground(new java.awt.Color(255, 102, 102));
        jBRealidadeVirtual.setForeground(new java.awt.Color(255, 255, 255));
        jBRealidadeVirtual.setText("Realidade Virtual");
        jBRealidadeVirtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRealidadeVirtualActionPerformed(evt);
            }
        });

        jBEspecial.setBackground(new java.awt.Color(255, 255, 255));
        jBEspecial.setForeground(new java.awt.Color(255, 102, 102));
        jBEspecial.setText("Especial");
        jBEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEspecialActionPerformed(evt);
            }
        });

        jLCadastrarFilmes.setBackground(new java.awt.Color(0, 153, 153));
        jLCadastrarFilmes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLCadastrarFilmes.setForeground(new java.awt.Color(255, 102, 102));
        jLCadastrarFilmes.setText("CADASTRAR FILMES:");

        jBCancelar.setBackground(new java.awt.Color(255, 102, 102));
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLCadastrarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jBFilmesNormais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBFilmes3d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBRealidadeVirtual, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jBEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLCadastrarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBFilmesNormais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBFilmes3d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRealidadeVirtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCancelar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBFilmes3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFilmes3dActionPerformed
        new Filme3d(this.listaFilmes).setVisible(true);
    }//GEN-LAST:event_jBFilmes3dActionPerformed

    private void jBRealidadeVirtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRealidadeVirtualActionPerformed
       new TelaRealidadeVirtual(this.listaFilmes).setVisible(true);
    }//GEN-LAST:event_jBRealidadeVirtualActionPerformed

    private void jBFilmesNormaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFilmesNormaisActionPerformed
        new TelaCadastro(this.listaFilmes).setVisible(true);
        
    }//GEN-LAST:event_jBFilmesNormaisActionPerformed

    private void jBEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEspecialActionPerformed
      new TelaEspecial(this.listaFilmes).setVisible(true);
    }//GEN-LAST:event_jBEspecialActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
    dispose();

    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEspecial;
    private javax.swing.JButton jBFilmes3d;
    private javax.swing.JButton jBFilmesNormais;
    private javax.swing.JButton jBRealidadeVirtual;
    private javax.swing.JLabel jLCadastrarFilmes;
    // End of variables declaration//GEN-END:variables
}
