/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rebéca
 */
public class Filme3d extends javax.swing.JFrame {
     LinkedList<Filmes> listaFilmes;
    
    public Filme3d(LinkedList<Filmes> listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
    }

    /**
    public CADASTRAR(LinkedList<Filmes> listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLGenero = new javax.swing.JLabel();
        jLDuracao = new javax.swing.JLabel();
        jLValor = new javax.swing.JLabel();
        jLDiretor = new javax.swing.JLabel();
        jLIndicacao = new javax.swing.JLabel();
        jLQuantOculos = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jCBGenero = new javax.swing.JComboBox<>();
        jTFDuracao = new javax.swing.JTextField();
        jTFPreco = new javax.swing.JTextField();
        jTFDiretor = new javax.swing.JTextField();
        jCBQuantOculos = new javax.swing.JComboBox<>();
        jBEnviar = new javax.swing.JButton();
        jCBIndicacao = new javax.swing.JComboBox<>();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FILMES 3D");

        jLNome.setText("Nome");

        jLGenero.setText("Gênero");

        jLDuracao.setText("Duração");

        jLValor.setText("Valor");

        jLDiretor.setText("Diretor");

        jLIndicacao.setText("Indicação");

        jLQuantOculos.setText("Quant Óculos");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jCBGenero.setBackground(new java.awt.Color(255, 102, 102));
        jCBGenero.setForeground(new java.awt.Color(255, 255, 255));
        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< SELECIONE >>", "1-Comédia", "2-Ação", "3-Romance", "4-Terror", "5-Ficção Científica", "6-Drama", "7-Documentario" }));

        jCBQuantOculos.setBackground(new java.awt.Color(255, 102, 102));
        jCBQuantOculos.setForeground(new java.awt.Color(255, 255, 255));
        jCBQuantOculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<SELECIONE>>", "10", "20", "30", "40", "50" }));

        jBEnviar.setBackground(new java.awt.Color(255, 102, 102));
        jBEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jBEnviar.setText("Enviar");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jCBIndicacao.setBackground(new java.awt.Color(255, 102, 102));
        jCBIndicacao.setForeground(new java.awt.Color(255, 255, 255));
        jCBIndicacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>>", "10 Anos", "12 Anos", "14 Anos", "16 Anos", "18 Anos" }));

        jBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBCancelar.setForeground(new java.awt.Color(255, 102, 102));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEnviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLDuracao)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLDiretor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLQuantOculos)
                                .addComponent(jLIndicacao))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCBQuantOculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                                .addComponent(jTFDuracao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFDiretor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBIndicacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGenero)
                    .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDuracao)
                    .addComponent(jTFDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValor)
                    .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDiretor)
                    .addComponent(jTFDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantOculos)
                    .addComponent(jCBQuantOculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIndicacao)
                    .addComponent(jCBIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCancelar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
       if(!jTFNome.getText().equals("")){
            if(jCBGenero.getSelectedIndex() != 0){
                boolean aux = SoTemNumeros(jTFDuracao.getText());
                if((!jTFDuracao.getText().equals("")) && (aux == true)){
                    aux = SoTemNumeros(jTFPreco.getText());
                    if((!jTFPreco.getText().equals("")) &&( aux == true)){
                        if(!jTFDiretor.getText().equals("")){
                            if(jCBQuantOculos.getSelectedIndex() != 0){
                                if(jCBIndicacao.getSelectedIndex() != 0){
                                    String nome = jTFNome.getText();
                                    int genero = jCBGenero.getSelectedIndex();
                                    int duracao = Integer.parseInt(jTFDuracao.getText());
                                    float preco = Float.parseFloat(jTFPreco.getText());//PERGUNTAR SE ta certo
                                    String diretor = jTFDiretor.getText();
                                    int quantOculos = jCBQuantOculos.getSelectedIndex();
                                    int indicacao = jCBIndicacao.getSelectedIndex();
                                    DDD meuFilmeddd = new DDD(quantOculos, nome, genero, duracao, preco, diretor, indicacao);
                                    listaFilmes.add(meuFilmeddd);
                                    JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso!");
                                    limpaCampos();
                                    
                                }else{
                                  JOptionPane.showMessageDialog(rootPane, "Favor informar a indicação de idade.");   
                                }
                            }else{
                               JOptionPane.showMessageDialog(rootPane, "Favor informar a quantidade de oculos necessária.");  
                            }
                        }else{ JOptionPane.showMessageDialog(rootPane, "Favor informar o diretor do filme.");
                        }
                         
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Favor informar o valor do filme em números.!");
                    }
                     
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Favor informar a duração do filme em min");
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Favor informar o genero do filme.");
            } 
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Favor informar o nome do filme.");  
        }
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void limpaCampos(){
      jTFNome.setText("");
      jTFDuracao.setText("");
      jTFDiretor.setText("");
      jTFPreco.setText("");
      jCBGenero.setSelectedIndex(0);
      jCBIndicacao.setSelectedIndex(0);
      jCBQuantOculos.setSelectedIndex(0);
  }
    public boolean SoTemNumeros(String jTFDuracao) {
        try {
            Long.parseLong(jTFDuracao);
             return true;
            } catch (NumberFormatException e) {
      return false;
   }
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JComboBox<String> jCBGenero;
    private javax.swing.JComboBox<String> jCBIndicacao;
    private javax.swing.JComboBox<String> jCBQuantOculos;
    private javax.swing.JLabel jLDiretor;
    private javax.swing.JLabel jLDuracao;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLIndicacao;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLQuantOculos;
    private javax.swing.JLabel jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFDiretor;
    private javax.swing.JTextField jTFDuracao;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPreco;
    // End of variables declaration//GEN-END:variables
}
