/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TelaVisualizacao extends javax.swing.JFrame {
        LinkedList<Filmes> listaFilmes;
    /**
     * Creates new form TelaVisualizacao
     */
    public TelaVisualizacao(LinkedList<Filmes>listaFilmes) {
        initComponents();
        this.listaFilmes=listaFilmes;
        DefaultTableModel modelo = (DefaultTableModel) jTFilmes.getModel();
        modelo.setNumRows(0);//SERVE PARA REINICIAR A TABELA 
        
        int posicaoTabela = 0;
        /*
        int posicaoTabela1 = 0;
        int posicaoTabela2 = 0;
        int posicaoTabela3 = 0;
        */
        for(int x=0; x<this.listaFilmes.size(); x++){
            
            Filmes meuFilme = this.listaFilmes.get(x);
           
            modelo.addRow(new Object[]{});
            modelo.setValueAt(meuFilme.getNome(), x, 0);
            if(meuFilme instanceof DDD){
               modelo.setValueAt("3 D", x, 1);
                
                
                
            }else if(meuFilme instanceof Especial){
                modelo.setValueAt("Especial", x, 1);
                
            }else if(meuFilme instanceof RealidadeVirtual){
                modelo.setValueAt("Realidade Virtual", x, 1);
            }else{
                  modelo.setValueAt("Normais", x, 1);
            }
        }
    }
                                       

    
    
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTFilmes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBDetalhar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFilmes.setBackground(new java.awt.Color(255, 102, 102));
        jTFilmes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTFilmes.setForeground(new java.awt.Color(255, 255, 255));
        jTFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Filmes", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTFilmes);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("SEUS FILMES CADASTRADOS");

        jBDetalhar.setBackground(new java.awt.Color(255, 255, 255));
        jBDetalhar.setForeground(new java.awt.Color(255, 102, 102));
        jBDetalhar.setText("Detalhar");
        jBDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetalharActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDetalhar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDetalhar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(102, 102, 102))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetalharActionPerformed
    int indice= jTFilmes.getSelectedRow();
        if (indice != -1)
        {
            Filmes meuFilme = this.listaFilmes.get(indice);
            JOptionPane.showMessageDialog(rootPane, "Nome: "+meuFilme.getNome()+"\nGênero: "+meuFilme.getGenero()+"\nDuração: " + meuFilme.getDuracao()+ "min" + "\nValor: "+ meuFilme.getPreco() +"\nDiretor " + meuFilme.getDiretor() + "\nIndicação: " + meuFilme.getIndicacao() );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Você deve selecionar um Filme antes de clicar em detalhar.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jBDetalharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetalhar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFilmes;
    // End of variables declaration//GEN-END:variables
}
