/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaRealidadeVirtual extends javax.swing.JFrame {
    LinkedList<Filmes>listaFilmes;
    /**
     * Creates new form TelaRealidadeVirtual
     */
    public TelaRealidadeVirtual(LinkedList<Filmes>listaFilmes) {
        initComponents();
         this.listaFilmes = listaFilmes;
    }

    /**
     *  this.listaFilmes = listaFilmes;
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFDuracao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFPreco = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jTFDiretor = new javax.swing.JTextField();
        jLGenero = new javax.swing.JLabel();
        jCBQuantOculos = new javax.swing.JComboBox<>();
        jLDuracao = new javax.swing.JLabel();
        jBEnviar = new javax.swing.JButton();
        jLValor = new javax.swing.JLabel();
        jCBIndicacao = new javax.swing.JComboBox<>();
        jLDiretor = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jLIndicacao = new javax.swing.JLabel();
        jLQuantOculos = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jCBGenero = new javax.swing.JComboBox<>();
        jLQuantFone = new javax.swing.JLabel();
        jCBQuantFone = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFDuracao.setToolTipText("Informe a duração em minutos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FILMES DE REALIDADE VIRTUAL");

        jLNome.setText("Nome");

        jLGenero.setText("Gênero");

        jCBQuantOculos.setBackground(new java.awt.Color(255, 102, 102));
        jCBQuantOculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<SELECIONE>>", "10", "20", "30", "40", "50", " " }));

        jLDuracao.setText("Duração");

        jBEnviar.setBackground(new java.awt.Color(255, 102, 102));
        jBEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jBEnviar.setText("Enviar");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jLValor.setText("Valor");

        jCBIndicacao.setBackground(new java.awt.Color(255, 102, 102));
        jCBIndicacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>>", "10 Anos", "12 Anos", "14 Anos", "16 Anos", "18 Anos" }));

        jLDiretor.setText("Diretor");

        jBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBCancelar.setForeground(new java.awt.Color(255, 102, 102));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLIndicacao.setText("Indicação");

        jLQuantOculos.setText("Quant Óculos");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jCBGenero.setBackground(new java.awt.Color(255, 102, 102));
        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< SELECIONE >>", "1-Comédia", "2-Ação", "3-Romance", "4-Terror", "5-Ficção Científica", "6-Drama", "7-Documentario" }));

        jLQuantFone.setText("Quant Fone");

        jCBQuantFone.setBackground(new java.awt.Color(255, 102, 102));
        jCBQuantFone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>>", "10 ", "20", "30", "40", "50" }));
        jCBQuantFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBQuantFoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLQuantFone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCBQuantFone, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLGenero, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLDuracao)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLDiretor, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLQuantOculos)
                                .addComponent(jLIndicacao))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCBQuantOculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCBGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFDuracao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFDiretor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jCBIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGenero)
                    .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDuracao)
                    .addComponent(jTFDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValor)
                    .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDiretor)
                    .addComponent(jTFDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantOculos)
                    .addComponent(jCBQuantOculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantFone)
                    .addComponent(jCBQuantFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIndicacao))
                .addGap(18, 18, 18)
                .addComponent(jBEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCancelar)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        if(!jTFNome.getText().equals("")){
            if(jCBGenero.getSelectedIndex() != 0){
                 boolean aux = SoTemNumeros(jTFDuracao.getText());
                if((!jTFDuracao.getText().equals("")) && (aux == true)){
                    aux = SoTemNumeros(jTFPreco.getText());
                    if((!jTFPreco.getText().equals("")) &&( aux == true)){
                        if(!jTFDiretor.getText().equals("")){
                            if(jCBQuantOculos.getSelectedIndex() != 0){
                                if(jCBQuantFone.getSelectedIndex() != 0){
                                    if(jCBIndicacao.getSelectedIndex() != 0){
                                    String nome = jTFNome.getText();
                                    int genero = jCBGenero.getSelectedIndex();
                                   int duracao = Integer.parseInt(jTFDuracao.getText());
                                    float preco = Float.parseFloat(jTFPreco.getText());//PERGUNTAR SE ta certo
                                    String diretor = jTFDiretor.getText();
                                    int quantOculos = jCBQuantOculos.getSelectedIndex();
                                    
                                    int indicacao = jCBIndicacao.getSelectedIndex();
                                    RealidadeVirtual meuFilmeRealidadeVirtual = new RealidadeVirtual(genero, quantOculos, nome, genero, duracao, preco, diretor, indicacao);
                                   // DDD meuFilmeddd = new DDD(quantOculos, nome, genero, indicacao, preco, diretor, indicacao);
                                    listaFilmes.add(meuFilmeRealidadeVirtual);
                                    JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso!");
                                    limpaCampos();

                                }else{
                                    JOptionPane.showMessageDialog(rootPane, "Favor informar a indicação de idade.");
                                    }
                            }else{
                                JOptionPane.showMessageDialog(rootPane, "Favor informar a quantidade de fones necessários.");  
                                }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Favor informar a quantidade de oculos necessária.");
                            }
                    }else{ 
                        JOptionPane.showMessageDialog(rootPane, "Favor informar o diretor do filme.");
                         }

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Favor informar o valor do filme.!");
                    }

            }else{
                JOptionPane.showMessageDialog(rootPane, "Favor informar a duração do filme em min");
                }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Favor informar o genero do filme.");
            }

    }else{
        JOptionPane.showMessageDialog(rootPane, "Favor informar o nome do filme.");
        }
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jCBQuantFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBQuantFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBQuantFoneActionPerformed

    
      public void limpaCampos(){
      jTFNome.setText("");
      jTFDuracao.setText("");
      jTFDiretor.setText("");
      jTFPreco.setText("");
      jCBGenero.setSelectedIndex(0);
      jCBIndicacao.setSelectedIndex(0);
      jCBQuantOculos.setSelectedIndex(0);
      jCBQuantFone.setSelectedIndex(0);
  }
    public boolean SoTemNumeros(String jTFDuracao) {
        try {
            Long.parseLong(jTFDuracao);
             return true;
            } catch (NumberFormatException e) {
      return false;
   }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JComboBox<String> jCBGenero;
    private javax.swing.JComboBox<String> jCBIndicacao;
    private javax.swing.JComboBox<String> jCBQuantFone;
    private javax.swing.JComboBox<String> jCBQuantOculos;
    private javax.swing.JLabel jLDiretor;
    private javax.swing.JLabel jLDuracao;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLIndicacao;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLQuantFone;
    private javax.swing.JLabel jLQuantOculos;
    private javax.swing.JLabel jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFDiretor;
    private javax.swing.JTextField jTFDuracao;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPreco;
    // End of variables declaration//GEN-END:variables
}
