/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaEspecial extends javax.swing.JFrame {
     LinkedList<Filmes>listaFilmes;
    /**
     * Creates new form TelaEspecial
     */
    public TelaEspecial(LinkedList<Filmes>listaFilmes) {
        initComponents();
         this.listaFilmes = listaFilmes;
    }

    /**
     * 
     * 
     *  
public class TelaCadastro extends javax.swing.JFrame {
    LinkedList<Filmes>listaFilmes;
    /**
     * Creates new form TelaCadastro
     
    public TelaCadastro(LinkedList<Filmes>listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
    }
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bGInterprete = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        bGAudiodescri = new javax.swing.ButtonGroup();
        jTFPreco = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jTFDiretor = new javax.swing.JTextField();
        jLGenero = new javax.swing.JLabel();
        jLDuracao = new javax.swing.JLabel();
        jBEnviar = new javax.swing.JButton();
        jLValor = new javax.swing.JLabel();
        jCBIndicacao = new javax.swing.JComboBox<>();
        jLDiretor = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jLIndicacao = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jCBGenero = new javax.swing.JComboBox<>();
        jTFDuracao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPInterprete = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCBInterprete = new javax.swing.JComboBox<>();
        jLNomeInter = new javax.swing.JLabel();
        jTFNomeInter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTFInterprete = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCBDescricao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTFIdioma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBAudioDes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNome.setText("Nome");

        jLGenero.setText("Gênero");

        jLDuracao.setText("Duração");

        jBEnviar.setBackground(new java.awt.Color(255, 102, 102));
        jBEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jBEnviar.setText("Enviar");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jLValor.setText("Valor");

        jCBIndicacao.setBackground(new java.awt.Color(255, 102, 102));
        jCBIndicacao.setForeground(new java.awt.Color(255, 255, 255));
        jCBIndicacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>>", "10 Anos", "12 Anos", "14 Anos", "16 Anos", "18 Anos" }));

        jLDiretor.setText("Diretor");

        jBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBCancelar.setForeground(new java.awt.Color(255, 102, 102));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLIndicacao.setText("Indicação");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jCBGenero.setBackground(new java.awt.Color(255, 102, 102));
        jCBGenero.setForeground(new java.awt.Color(255, 255, 255));
        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< SELECIONE >>", "1-Comédia", "2-Ação", "3-Romance", "4-Terror", "5-Ficção Científica", "6-Drama", "7-Documentario" }));

        jTFDuracao.setToolTipText("Favor informar a duração em minutos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FILMES ESPECIAIS");

        jPInterprete.setBackground(new java.awt.Color(255, 102, 102));
        jPInterprete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 102), null, null));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Interprete?");

        jCBInterprete.setForeground(new java.awt.Color(255, 102, 102));
        jCBInterprete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jCBInterprete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBInterpreteActionPerformed(evt);
            }
        });

        jLNomeInter.setForeground(new java.awt.Color(255, 255, 255));
        jLNomeInter.setText("Nome");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF");

        try {
            jFTFInterprete.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPInterpreteLayout = new javax.swing.GroupLayout(jPInterprete);
        jPInterprete.setLayout(jPInterpreteLayout);
        jPInterpreteLayout.setHorizontalGroup(
            jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInterpreteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInterpreteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jCBInterprete, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInterpreteLayout.createSequentialGroup()
                        .addGroup(jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNomeInter)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTFInterprete, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jTFNomeInter))))
                .addGap(21, 21, 21))
        );
        jPInterpreteLayout.setVerticalGroup(
            jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInterpreteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBInterprete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNomeInter)
                    .addComponent(jTFNomeInter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInterpreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jFTFInterprete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descrição");

        jCBDescricao.setForeground(new java.awt.Color(255, 102, 102));
        jCBDescricao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jCBDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDescricaoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Idioma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(jCBDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTFIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCBDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Audio Descr");

        jCBAudioDes.setBackground(new java.awt.Color(255, 102, 102));
        jCBAudioDes.setForeground(new java.awt.Color(255, 255, 255));
        jCBAudioDes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<SELECIONE>>", "Sim", "Não" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLDuracao)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLDiretor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLIndicacao))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jTFDuracao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDiretor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBIndicacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBAudioDes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPInterprete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNome)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLGenero)
                            .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDuracao)
                            .addComponent(jTFDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLValor)
                            .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDiretor))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLIndicacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBAudioDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jPInterprete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBEnviar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        if(!jTFNome.getText().equals("")){
            if(jCBGenero.getSelectedIndex() != 0){
               boolean aux = SoTemNumeros(jTFDuracao.getText());
                 if((!jTFDuracao.getText().equals("")) && (aux == true)){
                    aux = SoTemNumeros(jTFPreco.getText());
                    if((!jTFPreco.getText().equals("")) &&( aux == true)){
                        if(!jTFDiretor.getText().equals("")){        
                                if(jCBIndicacao.getSelectedIndex() != 0){
                                    if(jCBAudioDes.getSelectedIndex() != 0){
                                        
                                       String nome = jTFNome.getText();
                                        int genero = jCBGenero.getSelectedIndex();
                                        int duracao = Integer.parseInt(jTFDuracao.getText());
                                        float preco = Float.parseFloat(jTFPreco.getText());//PERGUNTAR SE ta certo
                                        String diretor = jTFDiretor.getText();
                                        int indicacao = jCBIndicacao.getSelectedIndex();
                                        int audioDescr= jCBAudioDes.getSelectedIndex();
                                        
                                       if( (jCBDescricao.getSelectedIndex() == 0) && jCBInterprete.getSelectedIndex() == 0){
                                            Especial meuFilmeEspecial= new Especial(audioDescr, nome, genero, duracao, preco, diretor, indicacao);
                                            this.listaFilmes.add(meuFilmeEspecial);
                                            JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso! ");
                                            limpaCampos();
                                       }else if((jCBDescricao.getSelectedIndex()== 1) && jCBInterprete.getSelectedIndex() == 0){
                                           if(!jTFIdioma.getText().equals("")){
                                               int descricao = jCBDescricao.getSelectedIndex();
                                               String idioma = jTFIdioma.getText();
                                               Especial meuFilmeEspecial = new Especial(descricao, idioma, audioDescr, nome, genero, duracao, preco, diretor, indicacao);
                                               this.listaFilmes.add(meuFilmeEspecial); 
                                               JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso!");
                                               limpaCampos();
                                           }else{
                                               JOptionPane.showMessageDialog(rootPane, "ESCREVE A PORARIA DO IDIOMA QUE EU JÁ TO FICANDO LOUCA!!");
                                           }
                                       }else if((jCBDescricao.getSelectedIndex()== 0) &&( jCBInterprete.getSelectedIndex() == 1)){
                                            if(!jTFNomeInter.getText().equals("")){
                                                
                                                if(!jFTFInterprete.getText().equals("")){
                                                 int interprete = jCBInterprete.getSelectedIndex();
                                                String nomeInter = jTFNomeInter.getText();
                                                String cpf =  jFTFInterprete.getText(); // PERHUNTAR SOR COMO QUE FAZ PRA ISSO COLOCAR ARRUMAR SOCORRO NÃO SEI MAIS OQ TA ACONTESENDOOOOOOOOOOO AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                                                Especial meuFilmeEspecial = new Especial(interprete, nomeInter, nomeInter, audioDescr, nome, genero, duracao, preco, diretor, indicacao);
                                                this.listaFilmes.add(meuFilmeEspecial);
                                                JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso!");
                                                limpaCampos();
                                                }else{
                                                    JOptionPane.showMessageDialog(rootPane, "ESCREVE A PORARIA DO CPF QUE EU JÁ TO FICANDO LOUCA!!"); 
                                                }
                                                
                                            }else{
                                                JOptionPane.showMessageDialog(rootPane, "ESCREVE A PORARIA DO NOME QUE EU JÁ TO FICANDO LOUCA!!");
                                            }
                                       }else if((jCBDescricao.getSelectedIndex()== 1) &&( jCBInterprete.getSelectedIndex() == 1)){
                                           if(!jTFIdioma.getText().equals("")){
                                                if(!jTFNomeInter.getText().equals("")){
                                                    aux = SoTemNumeros(jTFDuracao.getText());
                                                    if((!jFTFInterprete.getText().equals("")) && (aux == true)){
                                                        int descricao = jCBDescricao.getSelectedIndex();
                                                         String idioma = jTFIdioma.getText();   
                                                         String nomeInter = jTFNomeInter.getText();
                                                         String cpf =  jFTFInterprete.getText(); //// CPFFFFFFFFFFF COM PROBLEMAAAAAAAAAAAAAAAAA
                                                         int interprete = jCBInterprete.getSelectedIndex();
                                                         Especial meuFilmeEspecial = new Especial(interprete, nomeInter, nomeInter, descricao, idioma, audioDescr, nome, genero, duracao, preco, diretor, indicacao);
                                                         this.listaFilmes.add(meuFilmeEspecial);
                                                         JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso!");
                                                         limpaCampos();
                                                    }else {
                                                   JOptionPane.showMessageDialog(rootPane, "ESCREVE A PORARIA DO CPF QUE EU JÁ TO FICANDO LOUCA!!");  
                                                    }   
                                                }else{
                                                     JOptionPane.showMessageDialog(rootPane, "ESCREVE A PORARIA DO NOME QUE EU JÁ TO FICANDO LOUCA!!");
                                                }
                                                
                                                    
                                            }else{
                                                JOptionPane.showMessageDialog(rootPane, "ESCREVE A PORARIA DO IDIOMA QUE EU JÁ TO FICANDO LOUCA!!");
                                           }
                                       }
                                       
                                              
                                    }else{
                                         JOptionPane.showMessageDialog(rootPane, "Selecione alguma coisa ai QUE EU JÁ TO FICANDO LOUCA!!");
                                    }
                               }else{
                                    JOptionPane.showMessageDialog(rootPane, "Favor informar a indicação de idade.");
                                }
                          
                        }else{ JOptionPane.showMessageDialog(rootPane, "Favor informar o diretor do filme.");
                        }

                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Favor informar o valor do filme.!");
                    }

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Favor informar a duração do filme em min");
                }

            }else{
                JOptionPane.showMessageDialog(rootPane, "Favor informar o genero do filme.");
            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Favor informar o nome do filme.");
                                    
                                   
        }
                  
   
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jCBDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDescricaoActionPerformed
        if(jCBDescricao.getSelectedIndex() == 0){
          jTFIdioma.setEnabled(false);
        }else{
             jTFIdioma.setEnabled(true); 
        }      
    }//GEN-LAST:event_jCBDescricaoActionPerformed

    private void jCBInterpreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBInterpreteActionPerformed
        if(jCBInterprete.getSelectedIndex() == 0){
            jTFNomeInter.setEnabled(false);
            jFTFInterprete.setEnabled(false);
        }else{
            jTFNomeInter.setEnabled(true);
            jFTFInterprete.setEnabled(true);  
        }
    }//GEN-LAST:event_jCBInterpreteActionPerformed

    /**
     * @param args the command line arguments
     */
   public void limpaCampos()
    {
        jTFNome.setText("");
        jTFDiretor.setText("");
        jTFDuracao.setText("");
        jTFIdioma.setText("");
        jTFNomeInter.setText("");
        jTFPreco.setText("");
        jFTFInterprete.setText("");
        jCBGenero.setSelectedIndex(0);
        jCBDescricao.setSelectedIndex(0);
        jCBAudioDes.setSelectedIndex(0);
        jCBIndicacao.setSelectedIndex(0);
        jCBInterprete.setSelectedIndex(0);
    }
    public boolean SoTemNumeros(String jTFDuracao) {
        try {
            Long.parseLong(jTFDuracao);
             return true;
            } catch (NumberFormatException e) {
      return false;
   }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGAudiodescri;
    private javax.swing.ButtonGroup bGInterprete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JComboBox<String> jCBAudioDes;
    private javax.swing.JComboBox<String> jCBDescricao;
    private javax.swing.JComboBox<String> jCBGenero;
    private javax.swing.JComboBox<String> jCBIndicacao;
    private javax.swing.JComboBox<String> jCBInterprete;
    private javax.swing.JFormattedTextField jFTFInterprete;
    private javax.swing.JLabel jLDiretor;
    private javax.swing.JLabel jLDuracao;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLIndicacao;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNomeInter;
    private javax.swing.JLabel jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPInterprete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFDiretor;
    private javax.swing.JTextField jTFDuracao;
    private javax.swing.JTextField jTFIdioma;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNomeInter;
    private javax.swing.JTextField jTFPreco;
    // End of variables declaration//GEN-END:variables
}
