/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaRelatorio extends javax.swing.JFrame {
    LinkedList<Filmes>listaFilmes;

  /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio(LinkedList<Filmes> listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBQuantFilmes = new javax.swing.JCheckBox();
        jCBQuantFilmeEspeci = new javax.swing.JCheckBox();
        jCBQuantFilme3d = new javax.swing.JCheckBox();
        jCBQuantRealidadeVirtu = new javax.swing.JCheckBox();
        jCBMediaValores = new javax.swing.JCheckBox();
        jBVerificar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("ESCOLHA O QUE DESEJA:");

        jCBQuantFilmes.setBackground(new java.awt.Color(255, 255, 255));
        jCBQuantFilmes.setText("Quantidade de Filmes Cadastrados");

        jCBQuantFilmeEspeci.setBackground(new java.awt.Color(255, 102, 102));
        jCBQuantFilmeEspeci.setText("Quantidade de Filmes Especiais");

        jCBQuantFilme3d.setBackground(new java.awt.Color(255, 255, 255));
        jCBQuantFilme3d.setText("Quantidade de Filmes 3d");

        jCBQuantRealidadeVirtu.setBackground(new java.awt.Color(255, 102, 102));
        jCBQuantRealidadeVirtu.setText("Quantidade de Filmes de Realidade Virrtual");

        jCBMediaValores.setBackground(new java.awt.Color(255, 255, 255));
        jCBMediaValores.setText("Média dos Valores");

        jBVerificar.setBackground(new java.awt.Color(255, 255, 255));
        jBVerificar.setForeground(new java.awt.Color(255, 102, 102));
        jBVerificar.setText("Verificar");
        jBVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarActionPerformed(evt);
            }
        });

        jBCancelar.setBackground(new java.awt.Color(255, 102, 102));
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBQuantRealidadeVirtu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCBQuantFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBQuantFilme3d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBQuantFilmeEspeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCBMediaValores, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCBQuantFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBQuantFilmeEspeci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBQuantFilme3d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBQuantRealidadeVirtu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBMediaValores)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVerificar)
                    .addComponent(jBCancelar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();       
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarActionPerformed
      //VERIFICAR QUANTOS FILMES DE CADA UM
        int quantFilmesNormais = 0;
        int quantFilmes3d =0;
        int quantFilmesEspec = 0;
        int quantRealidaVirt =0;
        float valor =0;
        float outroValor =0;
        int aux =0;
        //VERIFICAR QUANTOS FILMES DE CADA UM
        for(int x=0; x<this.listaFilmes.size(); x++){
            Filmes meuFilme = this.listaFilmes.get(x);
            
            quantFilmesNormais ++;
            
             if(meuFilme instanceof DDD){
                quantFilmes3d ++;
            }else if(meuFilme instanceof Especial){
                quantFilmesEspec ++;
            }else if (meuFilme instanceof RealidadeVirtual){ //PERGUNTAR PRO SOR SE ESTOU FAZENDO ISSO CERTO
                quantRealidaVirt ++;
            }
        //VERIFICAR OS PREÇOS DE CADA UM PRA FAZER MÉDIA
             valor = meuFilme.getPreco() ;
             outroValor = valor + outroValor;
             aux++;   
            }
        float media = outroValor/aux;
           
        if(jCBQuantFilmes.isSelected()) {
           JOptionPane.showMessageDialog(rootPane, "Quantidade de Filmes cadastrados : " + listaFilmes.size());
           //SE NÃO DER TENTAR 
           //INT Total = ListaFilmes.size();
           //MOstrar total
       }
       if(jCBQuantFilmeEspeci.isSelected()){
        JOptionPane.showMessageDialog(rootPane, "Quantidade de filmes Especiais cadastrados: " + quantFilmesEspec );
       }
       if(jCBQuantFilme3d.isSelected()){
        JOptionPane.showMessageDialog(rootPane, "Quantidade de filmes 3d cadastrados: " + quantFilmes3d );
       }
       if(jCBQuantRealidadeVirtu.isSelected()){
        JOptionPane.showMessageDialog(rootPane, "Quantidade de filmes de Realidade Virtual cadastrados: " + quantRealidaVirt );
       }
       if(jCBMediaValores.isSelected()){
           JOptionPane.showMessageDialog(rootPane, "A média dos preçoes é: " + media);
       }

       limpaCampos();
  
    }//GEN-LAST:event_jBVerificarActionPerformed
public void limpaCampos(){
      jCBQuantFilmes.setSelected(false);
      jCBMediaValores.setSelected(false);
      jCBQuantFilme3d.setSelected(false);
      jCBQuantFilmeEspeci.setSelected(false);
      jCBQuantRealidadeVirtu.setSelected(false);
  }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBVerificar;
    private javax.swing.JCheckBox jCBMediaValores;
    private javax.swing.JCheckBox jCBQuantFilme3d;
    private javax.swing.JCheckBox jCBQuantFilmeEspeci;
    private javax.swing.JCheckBox jCBQuantFilmes;
    private javax.swing.JCheckBox jCBQuantRealidadeVirtu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
