/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaCadastro extends javax.swing.JFrame {
    LinkedList<Filmes>listaFilmes;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro(LinkedList<Filmes>listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
    }

   
    /**
     * public class CADASTRAR extends javax.swing.JFrame {
   LinkedList<Filmes> listaFilmes;
    
     
    Creates new form CADASTRAR
    
    public CADASTRAR(LinkedList<Filmes> listaFilmes) {
        initComponents();
        this.listaFilmes = listaFilmes;
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLNome = new javax.swing.JLabel();
        jLGenero = new javax.swing.JLabel();
        jLDuracao = new javax.swing.JLabel();
        jLIndicacao = new javax.swing.JLabel();
        jLValor = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jCBGenero = new javax.swing.JComboBox<>();
        jTFDuracao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLPreco = new javax.swing.JLabel();
        jTFPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLDiretor = new javax.swing.JLabel();
        jTFDiretor = new javax.swing.JTextField();
        jBEnviar = new javax.swing.JButton();
        jCBIndicacao = new javax.swing.JComboBox<>();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNome.setText("Nome");

        jLGenero.setText("Gênero");

        jLDuracao.setText("Duração");

        jLIndicacao.setText("Indicação");

        jLValor.setText("Valor");

        jCBGenero.setBackground(new java.awt.Color(255, 102, 102));
        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< SELECIONE >>", "1-Comédia", "2-Ação", "3-Romance", "4-Terror", "5-Ficção Científica", "6-Drama", "7-Documentario" }));

        jTFDuracao.setToolTipText("Colocar o tempo de duração em minutos");
        jTFDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDuracaoActionPerformed(evt);
            }
        });

        jTFPreco.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("CADASTRO DE FILMES!");

        jLDiretor.setText("Diretor");

        jTFDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiretorActionPerformed(evt);
            }
        });

        jBEnviar.setBackground(new java.awt.Color(255, 102, 102));
        jBEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jBEnviar.setText("ENVIAR");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jCBIndicacao.setBackground(new java.awt.Color(255, 102, 102));
        jCBIndicacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>>", "10 Anos", "12 Anos", "14 Anos", "16 Anos", "18 Anos" }));

        jBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBCancelar.setForeground(new java.awt.Color(255, 102, 102));
        jBCancelar.setText("CANCELAR");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLIndicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jLDiretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBIndicacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBGenero, 0, 156, Short.MAX_VALUE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTFDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTFPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTFDiretor, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDuracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValor)
                    .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDiretor)
                    .addComponent(jTFDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLIndicacao)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLPreco)))
                    .addComponent(jCBIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDuracaoActionPerformed

    private void jTFDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDiretorActionPerformed

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        if(!jTFNome.getText().equals("")){
            if(jCBGenero.getSelectedIndex() != 0){
               boolean aux = SoTemNumeros(jTFDuracao.getText());
                if((!jTFDuracao.getText().equals("")) && (aux == true)){
                    aux = SoTemNumeros(jTFPreco.getText());
                    if((!jTFPreco.getText().equals("")) &&( aux == true)){
                        if(!jTFDiretor.getText().equals("")){
                            if(jCBIndicacao.getSelectedIndex() !=0){
                             
                               String nome = jTFNome.getText();
                               int genero = jCBGenero.getSelectedIndex();
                               int duracao = Integer.parseInt(jTFDuracao.getText());
                               float preco = Float.parseFloat(jTFPreco.getText());//PERGUNTAR SE ta certo
                               String diretor = jTFDiretor.getText();
                               int indicacao = jCBIndicacao.getSelectedIndex();
                               Filmes meuFilme = new Filmes(nome, genero, duracao, preco, diretor, indicacao);
                               listaFilmes.add(meuFilme);
                               JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso!");
                               limpaCampos();
                               
                            }else {
                                JOptionPane.showMessageDialog(rootPane, "Favor informar a indicação de idade."); 
                            }
                           
                        }else {
                            JOptionPane.showMessageDialog(rootPane, "Favor informar o diretor do filme.");
                        }
                         
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Favor informar o valor do filme em números..!");
                    }
                     
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Favor informar a duração do filme em min");
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Favor informar o genero do filme.");
            } 
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Favor informar o nome do filme.");  
        }
        
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
  public void limpaCampos(){
      jTFNome.setText("");
      jTFDuracao.setText("");
      jTFDiretor.setText("");
      jTFPreco.setText("");
      jCBGenero.setSelectedIndex(0);
      jCBIndicacao.setSelectedIndex(0);
  }
  public boolean SoTemNumeros(String QueAntaQueSou) {
        try {
            Long.parseLong(QueAntaQueSou);
             return true;
            } catch (NumberFormatException e) {
      return false;
   }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JComboBox<String> jCBGenero;
    private javax.swing.JComboBox<String> jCBIndicacao;
    private javax.swing.JLabel jLDiretor;
    private javax.swing.JLabel jLDuracao;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLIndicacao;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPreco;
    private javax.swing.JLabel jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFDiretor;
    private javax.swing.JTextField jTFDuracao;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPreco;
    // End of variables declaration//GEN-END:variables
}
